// Browser side of deltas/preview.html (generated by deltas/preview.mjs).
// Renders the embedded model: sidebar, unified/split diff, op chips, and the op detail panel.
(() => {
  'use strict';

  const data = JSON.parse(document.getElementById('preview-data').textContent);
  const app = document.getElementById('app');
  const VIEW_KEY = 'omw-preview-view';
  const THEME_KEY = 'omw-preview-theme';

  const store = {
    get(key) {
      try {
        return localStorage.getItem(key);
      } catch (error) {
        return null;
      }
    },
    set(key, value) {
      try {
        localStorage.setItem(key, value);
      } catch (error) {
        /* storage is a convenience, not a requirement */
      }
    },
  };

  let view = store.get(VIEW_KEY) === 'split' ? 'split' : 'unified';
  let theme = store.get(THEME_KEY) || 'auto'; // auto | light | dark
  let openOpId = null;

  const media = window.matchMedia('(prefers-color-scheme: dark)');

  const esc = (value) =>
    String(value).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

  function effectiveTheme() {
    return theme === 'auto' ? (media.matches ? 'dark' : 'light') : theme;
  }

  function applyTheme() {
    document.documentElement.dataset.theme = effectiveTheme();
    const button = document.getElementById('theme-btn');
    if (button) button.textContent = 'Theme: ' + theme.charAt(0).toUpperCase() + theme.slice(1);
  }

  media.addEventListener('change', () => {
    if (theme === 'auto') applyTheme();
  });

  // ---- small render helpers -------------------------------------------------
  function partsHtml(text, list) {
    if (!list) return esc(text);
    return list.map((part) => (part.eq ? esc(part.text) : '<span class="hl">' + esc(part.text) + '</span>')).join('');
  }

  function cellHtml(cell) {
    if (!cell) return '<div class="cell empty"></div>';
    const text = partsHtml(cell.text, cell.parts);
    return (
      '<div class="cell ' +
      cell.k +
      '"><span class="ln">' +
      cell.n +
      '</span><span class="code">' +
      (text === '' ? '&nbsp;' : text) +
      '</span></div>'
    );
  }

  function opChip(id) {
    return '<button type="button" class="chip" data-op="' + esc(id) + '">' + esc(id) + '</button>';
  }

  function blockHead(id, owners) {
    return (
      '<div class="block-head" id="blk-' +
      id +
      '" data-owners="' +
      esc(owners.join(' ')) +
      '">' +
      owners.map(opChip).join('') +
      '</div>'
    );
  }

  function fileKey(skillIndex, fileIndex) {
    return skillIndex + '-' + fileIndex;
  }

  // ---- views ----------------------------------------------------------------
  function unifiedView(file, key) {
    let out = '';
    let rowIndex = 0;
    file.blocks.forEach((block, blockIndex) => {
      if (block.kind === 'chg') out += blockHead(key + '-' + blockIndex, block.owners);
      for (let r = 0; r < block.rowCount; r += 1) {
        const row = file.unified[rowIndex + r];
        const text = row.k === 'del' ? partsHtml(row.text, row.aParts) : row.k === 'add' ? partsHtml(row.text, row.bParts) : esc(row.text);
        out +=
          '<div class="row ' +
          row.k +
          '"><span class="ln">' +
          (row.an === null ? '' : row.an) +
          '</span><span class="ln">' +
          (row.bn === null ? '' : row.bn) +
          '</span><span class="code">' +
          (text === '' ? '&nbsp;' : text) +
          '</span></div>';
      }
      rowIndex += block.rowCount;
    });
    return out;
  }

  function splitView(file, key) {
    let out = '';
    let seen = -1;
    for (const row of file.split) {
      if (row.b !== seen) {
        seen = row.b;
        const block = file.blocks[row.b];
        if (block.kind === 'chg') out += blockHead(key + '-' + row.b, block.owners);
      }
      out += '<div class="srow">' + cellHtml(row.l) + cellHtml(row.r) + '</div>';
    }
    return out;
  }

  function fileSection(skillIndex, fileIndex, file) {
    const key = fileKey(skillIndex, fileIndex);
    const body = view === 'unified' ? unifiedView(file, key) : splitView(file, key);
    const ops = file.ops.length;
    return (
      '<section class="file" id="file-' +
      key +
      '">' +
      '<div class="file-head"><code>' +
      esc(file.path) +
      '</code>' +
      '<span class="stat"><span class="add">+' +
      file.added +
      '</span> <span class="del">&minus;' +
      file.removed +
      '</span></span>' +
      '<span class="muted">' +
      ops +
      ' op' +
      (ops === 1 ? '' : 's') +
      '</span></div>' +
      '<div class="diff ' +
      view +
      '">' +
      body +
      '</div></section>'
    );
  }

  function sidebar() {
    let out = '';
    data.skills.forEach((skill, skillIndex) => {
      out += '<div class="nav-skill">' + esc(skill.name) + '</div>';
      skill.files.forEach((file, fileIndex) => {
        out +=
          '<a class="nav-file" href="#file-' +
          fileKey(skillIndex, fileIndex) +
          '"><span>' +
          esc(file.path) +
          '</span><span class="muted">' +
          file.ops.length +
          '</span></a>';
        out += '<div class="nav-ops">';
        for (const op of file.ops) {
          out += '<button type="button" class="nav-op" data-op="' + esc(op.id) + '">' + esc(op.id.split('/').pop()) + '</button>';
        }
        out += '</div>';
      });
    });
    return out;
  }

  function topbar() {
    const stats = data.stats;
    let line = stats.skills + ' skills &middot; ' + stats.files + ' files &middot; ' + stats.ops + ' ops';
    if (stats.warnings) line += ' &middot; <span class="del">' + stats.warnings + ' warning(s)</span>';
    if (stats.drift) line += ' &middot; <span class="del">' + stats.drift + ' drift(s)</span>';
    return (
      '<header class="topbar">' +
      '<div class="brand">oh-my-wayfinder <span>&middot; mapping preview</span></div>' +
      '<div class="stats">' +
      line +
      '</div>' +
      '<div class="controls"><div class="segmented">' +
      '<button type="button" data-view="unified" class="' +
      (view === 'unified' ? 'active' : '') +
      '">Unified</button>' +
      '<button type="button" data-view="split" class="' +
      (view === 'split' ? 'active' : '') +
      '">Split</button>' +
      '</div><button type="button" id="theme-btn">Theme: Auto</button></div>' +
      '</header>'
    );
  }

  function banners() {
    let out = '';
    for (const warning of data.warnings) {
      out +=
        '<div class="banner">warning: ' +
        esc(warning.file + ':' + warning.line + (warning.opId ? ' (' + warning.opId + ')' : '') + ': ' + warning.message) +
        '</div>';
    }
    for (const item of data.drift) out += '<div class="banner">' + esc(item.message) + '</div>';
    return out;
  }

  function main() {
    let out = '';
    data.skills.forEach((skill, skillIndex) => {
      skill.files.forEach((file, fileIndex) => {
        out += fileSection(skillIndex, fileIndex, file);
      });
    });
    return out;
  }

  function render() {
    app.innerHTML =
      topbar() +
      banners() +
      '<div class="layout"><nav class="sidebar">' +
      sidebar() +
      '</nav><main class="main">' +
      main() +
      '</main></div><aside class="detail" id="detail" hidden></aside>';
    observeTopbar();
    applyTheme();
    if (openOpId) openOp(openOpId);
  }

  // The header is sticky and can wrap, so the sidebar and the detail drawer are anchored to
  // its measured height instead of a guess. Without this the drawer covers the view controls.
  let topbarObserver = null;

  function syncTopbarHeight() {
    const topbar = app.querySelector('.topbar');
    if (topbar) document.documentElement.style.setProperty('--topbar-h', topbar.offsetHeight + 'px');
  }

  function observeTopbar() {
    syncTopbarHeight();
    const topbar = app.querySelector('.topbar');
    if (!topbar || typeof ResizeObserver !== 'function') return;
    if (!topbarObserver) topbarObserver = new ResizeObserver(syncTopbarHeight);
    topbarObserver.disconnect();
    topbarObserver.observe(topbar);
  }

  window.addEventListener('resize', syncTopbarHeight);

  // ---- op detail ------------------------------------------------------------
  function findOp(id) {
    for (const skill of data.skills) {
      for (const file of skill.files) {
        const op = file.ops.find((candidate) => candidate.id === id);
        if (op) return { op, file };
      }
    }
    return null;
  }

  function segmentsHtml(list) {
    return list
      .map((part) => {
        if (part.k === 'eq') return esc(part.s);
        const cls = part.k === 'marker' ? 'marker' : part.k === 'find' ? 'find' : 'ins';
        return '<span class="' + cls + '">' + esc(part.s) + '</span>';
      })
      .join('');
  }

  function openOp(id) {
    const found = findOp(id);
    if (!found) return;
    const { op, file } = found;
    openOpId = id;

    let edits = '';
    if (op.edits.length > 0) {
      edits =
        '<h4>Edits (' +
        op.edits.length +
        ')</h4><div class="edits">' +
        op.edits
          .map(
            (edit) =>
              '<div class="edit"><pre class="del">' +
              esc(edit.find) +
              '</pre><pre class="add">' +
              esc(edit.content) +
              '</pre></div>',
          )
          .join('') +
        '</div>';
    }
    const insert = op.insert === null ? '' : '<h4>Insert</h4><pre class="add">' + esc(op.insert) + '</pre>';

    const detail = document.getElementById('detail');
    detail.innerHTML =
      '<div class="detail-head"><code>' +
      esc(op.id) +
      '</code><span><span class="muted">' +
      esc(file.path) +
      ' &middot; line ' +
      op.line +
      '</span> <button type="button" class="close">Close</button></span></div>' +
      '<div class="detail-body">' +
      (op.reason ? '<p class="reason">' + esc(op.reason) + '</p>' : '') +
      '<h4>Anchor (upstream text that gates this op)</h4><pre>' +
      segmentsHtml(op.anchorSegments) +
      '</pre>' +
      '<h4>Anchor after this op</h4><pre>' +
      segmentsHtml(op.afterSegments) +
      '</pre>' +
      edits +
      insert +
      '<h4>Defined in</h4><pre>deltas/mappings/' +
      esc(op.id.split('/')[0]) +
      '.md:' +
      op.line +
      '</pre></div>';
    detail.hidden = false;
  }

  // ---- interaction ----------------------------------------------------------
  function blocksOf(id) {
    return Array.from(document.querySelectorAll('.block-head')).filter((element) =>
      (element.dataset.owners || '').split(' ').includes(id),
    );
  }

  function setView(next) {
    if (view === next) return;
    view = next;
    store.set(VIEW_KEY, view);
    const scrollY = window.scrollY;
    render();
    window.scrollTo(0, scrollY);
  }

  function cycleTheme() {
    theme = theme === 'auto' ? 'light' : theme === 'light' ? 'dark' : 'auto';
    store.set(THEME_KEY, theme);
    applyTheme();
  }

  document.addEventListener('click', (event) => {
    const target = event.target;

    const viewButton = target.closest('[data-view]');
    if (viewButton) {
      setView(viewButton.dataset.view);
      return;
    }

    if (target.closest('#theme-btn')) {
      cycleTheme();
      return;
    }

    if (target.closest('.close')) {
      openOpId = null;
      document.getElementById('detail').hidden = true;
      return;
    }

    const opButton = target.closest('[data-op]');
    if (opButton) {
      const id = opButton.dataset.op;
      const blocks = blocksOf(id);
      if (opButton.classList.contains('nav-op') && blocks[0]) {
        blocks[0].scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
      document.querySelectorAll('.flash').forEach((element) => element.classList.remove('flash'));
      for (const block of blocks) block.classList.add('flash');
      openOp(id);
    }
  });

  document.addEventListener('keydown', (event) => {
    if (event.key === 'Escape' && !document.getElementById('detail').hidden) {
      openOpId = null;
      document.getElementById('detail').hidden = true;
    }
  });

  document.documentElement.dataset.theme = effectiveTheme();
  render();
})();
